services:
  ecg-dev:
    build:
      context: .
      target: builder
    volumes:
      - .:/home/user/project:ro
      - build-cache:/home/user/project/build
    environment:
      - DISPLAY=host.docker.internal:0.0
      - LIBGL_ALWAYS_INDIRECT=1
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
      - QT_DEBUG_PLUGINS=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: user
    command: sh -c "qt-cmake . -G Ninja -B ./build && cmake --build ./build && ./build/ECGProcessing"

  qt-designer:
    build:
      context: .
      target: builder
    volumes:
      - .:/home/user/project:rw  # Changed to rw to allow saving UI files
    environment:
      - DISPLAY=host.docker.internal:0.0
      - LIBGL_ALWAYS_INDIRECT=1
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: user
    command: designer

  ecg-prod:
    build:
      context: .
      target: runtime
    environment:
      - DISPLAY=host.docker.internal:0.0
      - LIBGL_ALWAYS_INDIRECT=1
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ecg-test:
    build:
      context: .
      target: builder
    volumes:
      - .:/home/user/project:ro
      - build-cache:/home/user/project/build
    user: user
    command: sh -c "cd build && ctest --output-on-failure"

volumes:
  build-cache: