name: Package gram_savitzky_golay
on:
  repository_dispatch:
    types:
    - package-master
    - package-release
  push:
    branches:
    - master
jobs:
  package:
    uses: jrl-umi3218/github-actions/.github/workflows/package-project.yml@master
    with:
      main-branch: master
      deps: '["jrl-umi3218/mc_state_observation"]'
      update-stable-and-head: true
      matrix: |
          {
            "dist": ["bionic", "focal", "jammy"],
            "arch": ["amd64"]
          }
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
